### PR TITLE
Add `modify_enchantment_level` power type.

### PR DESCRIPTION
**Pull request by ChrysanthCow**
This PR adds the Modify Enchantment Level power type from Apugli.

Accepts `enchantment`, `item_condition`, `modifier`, and `modifiers` fields.

This also slightly changes the `enchantment` entity/item conditions to make sure infinite recursion doesn't happen with this power applied and with the item/entity conditions linked to this power. It also adds a `use_modifications` field to both, which if false, you'll be able to check the original nbt tag.

### Minor Notes
- The redirects are necessary to make sure that enchantments work with an empty itemstack. If you rewrite to use MixinExtras, you can replace all of these with ModifyExpressionValues.
- Modifications to an item's cached enchantment list will only happen when necessary.
- Credits to @Jarva for the initial work and extra caching work done on this power type.
- This does rewrite the `EntityLinkedItemStack` interface to account for empty itemstacks.

### CODE REVIEW

**Comment by ChrysanthCow** [comment]
~~Please tell me if you want the item/entity conditions to check the original enchantment value instead of the modified one. Or if a field should be provided for this.~~

I have provided a field.

**Comment by ChrysanthCow** [comment]
This PR should now be ready.

**Comment by ChrysanthCow** [comment]
If you're wondering why I prioritise Apoli's holdingEntity value in ItemStackMixin within this PR.
1. I wanted to be less invasive in terms of vanilla code.
2. `ItemStack#getHolder` will always return null when empty.
```java
public Entity getHolder() {
    return !this.isEmpty() ? this.holder : null;
}
```

**Comment by ChrysanthCow** [comment]
Marked as a draft until I get the time to fix the newly arised StackOverflowError with the enchantment entity/item condition.

**Comment by ChrysanthCow** [comment]
It's ready again. 

`ModifyEnchantmentLevelPower#isInEnchantmentMap` exists because we need a safe way to bypass checking conditions when it comes to the enchantment entity/item conditions, but we also need a way to check if the power is available to the player.

**Review by eggohito — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
