### PR TITLE
Make the container type data type a bit more flexible

### PR DESCRIPTION
**Pull request by eggohito**
This PR refactors the container type data type to be a bit more flexible by adding the ability for developers to register a custom container type with its associated screen handler. This also lays the groundwork for a dynamic container type, where a user can define the columns and rows of the container type via datapacks. This also adds new container types, `generic_9xA`, where `A` is a number ranging from 1 to 6.

As of right now, dynamic container types are not done, but its current state should give a bit more freedom when providing more container types in the future, as it's no longer an enum.

### CODE REVIEW

**Comment by eggohito** [comment]
As of the current latest commit, container types now have their own dynamic screen handler using LibGui, meaning that users can now specify a container type in the power itself, as opposed to just using a pre-made container type. The old system of registering custom container types is still there for backwards compatibility and flexibility for adding pre-made container types

**Comment by ChrysanthCow** [comment]
Hi, is LibGui **absolutely necessary?**

I'm asking this because it'd be very detrimental to Origins Forge to have a mod in the Fabric version with no viable alternative existing. I know that y'all don't really care for this side of Origins, but I need to stand my ground here.

Would it be possible to handle this without the need for an extra library, that mind you, needs maintaining and all that.

**Comment by ChrysanthCow** [comment]
Pretty much, we'd have to maintain another project on top of the 5 already existing ones. (Origins Forge Master, Origins Forge, Apoli, Calio and Additional Entity Attributes). I'm cool with AEA because it's small and all that, but LibGui just seems like a daunting port for us.

I'd probably go for the route of recreating this system without LibGui, which would be a harder route, but I feel like it makes more sense from our end to not port an entire GUI library, and if that's theoretically do-able, I feel like Origins Fabric could drop the dependency.

**Comment by eggohito** [comment]
Yeah, you're right, another dependency is kinda wack. I'll see what I can do

**Comment by ChrysanthCow** [comment]
> Yeah, you're right, another dependency is kinda wack. I'll see what I can do

If you need any help with this, feel free to ask and I'll look into it with you.

**Comment by eggohito** [comment]
I managed to do it myself, which was a good challenge 🎉 I'm going to add a bit more stuff before finalizing stuff

**Comment by eggohito** [comment]
I'll be closing this PR due to the huge changes in upstream. I'll re-do this in the near future

**Pull request closed without merging**
