### PR TITLE
Rewrites to resolve memory leaking empty stack cache

### PR DESCRIPTION
**Pull request by ChrysanthCow**
The original code was my doing, so I felt I'd be the one to fix it.

# What this changes...
- Removed the empty stack cache in InventoryUtil and replaced it with one that only operates on entities with a ModifyEnchantmentLevel power.
- Changed Item Actions to utilise StackReferences instead of ItemStacks, this has the benefit of being a vanilla method for setting itemstacks, I've also removed MutableItemStack for this reason.
- "Workable" Empty Stacks (empty stacks that aren't on a global level) are now set during an item action being called inside a power, the InventoryUtil functions that change items or inside Modify Enchantment Level's new tick method (please do suggest better solutions if you have ideas), and also set condition meeting content in Modify Enchantment Level.

### CODE REVIEW

**Comment by eggohito** [comment]
Instead of having to use something like `ActionUtil`, perhaps `ActionFactory$Instance` could've been extended instead to differentiate between the action types

This could theoretically eliminate the breaking change and also prep. the groundwork for when actions are to be transformed into its own thing like powers are (e.g: in its own JSON file, with its own `Action` class for implementing functionality, which could also reference the power the action is in for better logging)

Though, this would be a lot more work compared to the current implementation

**Comment by ChrysanthCow** [comment]
> Instead of having to use something like `ActionUtil`, perhaps `ActionFactory$Instance` could've been extended instead to differentiate between the action types
> 
> This could theoretically eliminate the breaking change and also prep. the groundwork for when actions are to be transformed into its own thing like powers are (e.g: in its own JSON file, with its own `Action` class for implementing functionality, which could also reference the power the action is in for better logging)
> 
> Though, this would be a lot more work compared to the current implementation

I wanted to do that, but I couldn't think of a clean way without breaking backwards compat, although I did that anyways, so uhmmm... yeah.

**Comment by ChrysanthCow** [comment]
Here's my opinion on how we should go about this...

`ItemStack`s in Item Actions become `StackReference`. This was honestly a change I was considering bringing up for the rewrite, so it might be ideal to do it now. This is so `ItemStack#EMPTY` does not just operate on a global level. This would also deprecate the need for the `MutableItemStack` interface, and I think that'd be a good thing considering we are now utilising vanilla methods to change stacks.

We then create a new `ItemActionFactory` class, which has extra logic for `StackReference`s with `ItemStack#EMPTY`.

**Comment by ChrysanthCow** [comment]
# [Here is a migration guide I made for addon devs regarding this change](https://gist.github.com/MerchantPug/1e97f9496064bcdc46f48ef139398aea)

**Comment by ChrysanthCow** [comment]
You technically could've solved this by exclusively using a `WeakHashMap`, however, I feel that these rewrites were healthy for the project and I'd encourage them to be kept.

**Review by eggohito — APPROVED** [review]

**Comment by eggohito** [comment]
Alright, I've been double-checking this PR to prep. for merging, and everything seems to be fine now! I'll do another check tomorrow before merging

**Pull request merged**
