### PR TITLE
Add more loot context params. to the `modify` item action type

### PR DESCRIPTION
**Pull request by eggohito**
This PR adds a `position` vector field *(with default value of `{"x": 0, "y": 0, "z": 0}`),* and more loot context parameters to the `modify` item action type; more specifically, `THIS_ENTITY` *(the entity that has the item stack),* `TOOL` *(the item stack),* `BLOCK_STATE` *(the block state at the specified position),* and `BLOCK_ENTITY` *(the block entity at the specified position).*

This PR also adds new implementations, such as caching the "holder" of item stacks *(e.g: the entity that has the item stack),* and a new util. class: `StackReferenceUtil`, for getting an item stack with its "holder" from an entity's stack reference.

### CODE REVIEW

**Comment by eggohito** [comment]
I decided to add the `position` vector field and the `BLOCK_ENTITY` and `BLOCK_STATE` loot context parameters so that users can use the `minecraft:copy_nbt` and the `minecraft:copy_state` item modifiers to copy NBT data of a block entity and the block state properties of a block state respectively to the item being modified.

As for the `TOOL` loot context parameter, it's so that the users can evaluate a predicate on the item stack being modified in the item modifier

**Comment by apace100** [comment]
I definitely see the value of `THIS_ENTITY` where the stack holding entity is referenced.
However, I'm not sure what the block state and entity parameters can accomplish, when they are gathered from a position specified by the datapack developer. What would be a use-case for this?

**Comment by eggohito** [comment]
For the block entity context, it could be used for copying data from a block entity, such as the contents of a Shulker Box (or any container block) placed somewhere normally inaccessible to the item's NBT. Same goes for block state context, but instead of NBT data, it's copying the block state properties of the block.

Now that I think about it, it's not as flexible as I initially thought since the position is only relative to the item stack holder's dimension

**Comment by eggohito** [comment]
I decided to remove the `BLOCK_ENTITY` and `BLOCK_STATE` loot context parameters, as it wasn't really as flexible as I imagined, but I think the use-cases for those two parameters could be covered in an `execute_command` item action type or the `holder_action` item action type

**Pull request merged**
