### PR TITLE
Change the `inventory` power type a bit & add related entity action types

### PR DESCRIPTION
**Pull request by eggohito**
This PR changes the `inventory` power type a little bit by adding a `container_type` field that accepts `"hopper"`, `"dropper"`, `"dispenser"`, `"chest"` or `"double_chest"` enums, which has a default value of `"dropper"`. It also fixes a minor issue with the power type not dropping its contents if the power is lost.

It also adds a related entity action type named `modify_inventory_power`, which is an entity action type that can invoke an entity action type on the entity and an item action type on the items in either the specified slots, or items that fulfill the specified item condition type in the power that uses the `inventory` power type

### CODE REVIEW

**Comment by eggohito** [comment]
I've generalized `modify_inventory_power` to `modify_inventory`, which can now target player inventories, ender chest inventories and powers that use the `inventory` power type. (controlled by the `inventory_type` field)

I've also added two new entity action types: `replace_item` and `drop_item`, which can replace or drop item stacks in/from the specified slots or item stacks that fulfills the specified item condition type respectively. These new entity action types have a similar structure to `modify_inventory` (e.g: `inventory_type`, `slots`, etc.)

**Comment by eggohito** [comment]
The recent commit changes some stuff:

1. It added two new data types: `ApoliDataTypes.ITEM_SLOT` and `ApoliDataTypes.ITEM_SLOTS`, which refers to the "slot name" that one uses in the `/item` command (e.g: `container.x`, `inventory.x`, `enderchest.x`, etc.)

2. It added a new mixin, `ItemSlotArgumentTypeAccessor`, for accessing the private static `SLOT_NAMES_TO_SLOT_COMMAND_ID` field, which is a `Map<String, Integer>` of the default "slot names" and their corresponding slot ID.

3. It renamed the `apoli:drop_item` and `apoli:replace_item` entity action types to `apoli:drop_inventory` and `apoli:replace_inventory` respectively for consistency with `apoli:modify_inventory`.
*(I'm not quite sure if it should be those, or `apoli:drop_item`, `apoli:replace_item` and `apoli:modify_item` 🤔)*

4. It generalized (for real, this time) the `apoli:*_inventory` entity action types to work on entities that can have an inventory. It also removed the `InventoryType.ENDER_CHEST` enum (since you can already reference to the slots of an ender chest using "slot names") and renamed the `InventoryType.PLAYER` enum to `InventoryType.INVENTORY`.

**Comment by apace100** [comment]
Could you add a few example powers to the test data folder which allow testing the functionality of the changed power type and new actions?

I'll review this PR in detail in the coming days!

Thanks for the work on this so far. :)

**Comment by eggohito** [comment]
Ah! sure :D I'll add them in a bit. Thank you as well for your assistance, Apace!

**Pull request merged**
